# -*- coding: utf-8 -*-
"""DATAANALYST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ubXUscZVpbGF1yfF1GZ8RAfvYAzuUEXA
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd
import numpy as np
df = pd.read_csv("hotel_bookings.csv",encoding='latin-1')
print(f"Raw shape: {df.shape}")

df["children"] = df["children"].fillna(0)
df["country"] = df["country"].fillna("Unknown")
df["agent"] = df["agent"].fillna(0)
df["company"] = df["company"].fillna(0)

before = len(df)
df = df[(df["adults"] + df["children"] + df["babies"]) > 0]
df = df[df["adr"] >= 0]
adr_cap = df["adr"].quantile(0.99)
df["adr"] = np.where(df["adr"] > adr_cap, adr_cap, df["adr"])

df = df.drop_duplicates()

print(f"Removed {before - len(df)} invalid/duplicate rows -> {len(df)} rows remain")

month_map = {
    "January": 1, "February": 2, "March": 3, "April": 4,
    "May": 5, "June": 6, "July": 7, "August": 8,
    "September": 9, "October": 10, "November": 11, "December": 12
}
df["arrival_date_month_num"] = df["arrival_date_month"].map(month_map)

df["arrival_date"] = pd.to_datetime(
    dict(
        year=df["arrival_date_year"],
        month=df["arrival_date_month_num"],
        day=df["arrival_date_day_of_month"],
    ),
    errors="coerce",
)

df["reservation_status_date"] = pd.to_datetime(
    df["reservation_status_date"], errors="coerce"
)

df["total_nights"] = df["stays_in_weekend_nights"] + df["stays_in_week_nights"]
df["total_guests"] = df["adults"] + df["children"] + df["babies"]

# Drop rows with 0 nights
df = df[df["total_nights"] > 0]

# Lead time buckets
def lead_time_bucket(days):
    if days <= 7:
        return "0-7 days"
    elif days <= 30:
        return "8-30 days"
    elif days <= 90:
        return "31-90 days"
    else:
        return "90+ days"

df["lead_time_bucket"] = df["lead_time"].apply(lead_time_bucket)


df["estimated_revenue"] = df["adr"] * df["total_nights"]
df["revenue_at_risk"] = np.where(df["is_canceled"] == 1, df["estimated_revenue"], 0)


df["cancellation_status"] = df["is_canceled"].map({0: "Not Canceled", 1: "Canceled"})


df["has_deposit"] = np.where(df["deposit_type"] == "No Deposit", "No", "Yes")

print("\n--- Quick Sanity Checks ---")
print(f"Overall cancellation rate: {df['is_canceled'].mean():.2%}")
print(f"Total estimated revenue at risk: ${df['revenue_at_risk'].sum():,.0f}")
print("\nCancellation rate by deposit type:")
print(df.groupby("has_deposit")["is_canceled"].mean().round(3))
print("\nCancellation rate by lead time bucket:")
print(
    df.groupby("lead_time_bucket")["is_canceled"]
    .mean()
    .round(3)
    .reindex(["0-7 days", "8-30 days", "31-90 days", "90+ days"])
)

output_path = "hotel_bookings_clean.csv"
df.to_csv(output_path, index=False)
print(f"\nSaved cleaned dataset: {output_path}")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, classification_report, roc_auc_score
)

os.makedirs("eda_charts", exist_ok=True)

df = pd.read_csv("hotel_bookings_clean.csv")
print(f"Loaded cleaned dataset: {df.shape}")

cancel_counts = df["cancellation_status"].value_counts()
plt.figure(figsize=(5, 5))
plt.pie(cancel_counts, labels=cancel_counts.index, autopct="%1.1f%%",
        colors=["#4C72B0", "#DD8452"])
plt.title("Overall Cancellation Rate")
plt.savefig("eda_charts/1_overall_cancellation_rate.png", bbox_inches="tight")
plt.show()
plt.close()

seg_rate = df.groupby("market_segment")["is_canceled"].mean().sort_values(ascending=False)
plt.figure(figsize=(8, 5))
seg_rate.plot(kind="bar", color="#4C72B0")
plt.title("Cancellation Rate by Market Segment")
plt.ylabel("Cancellation Rate")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.savefig("eda_charts/2_cancellation_by_segment.png")
plt.show()
plt.close()

order = ["0-7 days", "8-30 days", "31-90 days", "90+ days"]
lead_rate = df.groupby("lead_time_bucket")["is_canceled"].mean().reindex(order)
plt.figure(figsize=(6, 5))
lead_rate.plot(kind="bar", color="#DD8452")
plt.title("Cancellation Rate by Lead Time")
plt.ylabel("Cancellation Rate")
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig("eda_charts/3_cancellation_by_leadtime.png")
plt.show()
plt.close()

month_order = ["January","February","March","April","May","June","July",
               "August","September","October","November","December"]
month_rate = df.groupby("arrival_date_month")["is_canceled"].mean().reindex(month_order)
plt.figure(figsize=(9, 5))
month_rate.plot(kind="line", marker="o", color="#55A868")
plt.title("Cancellation Rate by Arrival Month")
plt.ylabel("Cancellation Rate")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.savefig("eda_charts/4_cancellation_by_month.png")
plt.show()
plt.close()

rev_risk = df.groupby("hotel")["revenue_at_risk"].sum()
plt.figure(figsize=(5, 5))
rev_risk.plot(kind="bar", color="#C44E52")
plt.title("Total Revenue at Risk by Hotel Type")
plt.ylabel("Revenue at Risk ($)")
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig("eda_charts/5_revenue_at_risk_by_hotel.png")
plt.show()
plt.close()

features = [
    "lead_time", "arrival_date_month_num", "stays_in_weekend_nights",
    "stays_in_week_nights", "adults", "children", "babies",
    "is_repeated_guest", "previous_cancellations",
    "previous_bookings_not_canceled", "booking_changes",
    "days_in_waiting_list", "adr", "required_car_parking_spaces",
    "total_of_special_requests", "hotel", "meal", "market_segment",
    "distribution_channel", "reserved_room_type", "deposit_type",
    "customer_type",
]
target = "is_canceled"

X = df[features].copy()
y = df[target].copy()

numeric_cols = X.select_dtypes(include=np.number).columns.tolist()
categorical_cols = X.select_dtypes(include="object").columns.tolist()

preprocessor = ColumnTransformer(
    transformers=[
        ("num", "passthrough", numeric_cols),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols),
    ]
)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
print(f"\nTrain size: {X_train.shape[0]}, Test size: {X_test.shape[0]}")

log_reg_pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", LogisticRegression(max_iter=1000, random_state=42)),
])
log_reg_pipeline.fit(X_train, y_train)
y_pred_lr = log_reg_pipeline.predict(X_test)
y_proba_lr = log_reg_pipeline.predict_proba(X_test)[:, 1]

rf_pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(
        n_estimators=200, max_depth=12, random_state=42, n_jobs=-1
    )),
])
rf_pipeline.fit(X_train, y_train)
y_pred_rf = rf_pipeline.predict(X_test)
y_proba_rf = rf_pipeline.predict_proba(X_test)[:, 1]

def evaluate(name, y_true, y_pred, y_proba):
    return {
        "model": name,
        "accuracy": accuracy_score(y_true, y_pred),
        "precision": precision_score(y_true, y_pred),
        "recall": recall_score(y_true, y_pred),
        "f1": f1_score(y_true, y_pred),
        "roc_auc": roc_auc_score(y_true, y_proba),
    }

results = [
    evaluate("Logistic Regression", y_test, y_pred_lr, y_proba_lr),
    evaluate("Random Forest", y_test, y_pred_rf, y_proba_rf),
]
results_df = pd.DataFrame(results)

print("\n=== MODEL COMPARISON ===")
print(results_df.round(3).to_string(index=False))

# Confusion matrix for the better model (Random Forest)
cm = confusion_matrix(y_test, y_pred_rf)
print("\nRandom Forest Confusion Matrix:")
print(f"                Predicted No-Cancel  Predicted Cancel")
print(f"Actual No-Cancel      {cm[0][0]:>8}          {cm[0][1]:>8}")
print(f"Actual Cancel         {cm[1][0]:>8}          {cm[1][1]:>8}")

print("\nRandom Forest Classification Report:")
print(classification_report(y_test, y_pred_rf, target_names=["Not Canceled", "Canceled"]))

ohe_feature_names = rf_pipeline.named_steps["preprocessor"] \
    .named_transformers_["cat"].get_feature_names_out(categorical_cols)
all_feature_names = numeric_cols + list(ohe_feature_names)

importances = rf_pipeline.named_steps["classifier"].feature_importances_
feat_imp = pd.Series(importances, index=all_feature_names).sort_values(ascending=False).head(15)

plt.figure(figsize=(8, 6))
feat_imp.sort_values().plot(kind="barh", color="#4C72B0")
plt.title("Top 15 Feature Importances (Random Forest)")
plt.xlabel("Importance")
plt.tight_layout()
plt.savefig("feature_importance.png")
plt.show()
plt.close()

print("\nTop 10 most important features:")
print(feat_imp.head(10).round(4).to_string())

